feature/BPSINT-4-Bottom-Navigation Implementation
Blu3Parr0t/BPS_Internship_Winter_2021 pull request #2
Opened 2021-11-01 21:06 UTC by Inasity

Description: Added bottom sheet navigation to app.

Ticket: https://bpsinterns.atlassian.net/browse/BPSINT-4

2021-11-01 21:44 UTC, Blu3Parr0t commented on .gitignore
> +app/src/debug/res/values/google_maps_api.xml
remove this.

2021-11-01 21:44 UTC, Blu3Parr0t commented on app/src/debug/res/values/google_maps_api.xml
> +<resources>
remove this.

2021-11-01 21:55 UTC, Blu3Parr0t requested changes
Only include things that are relative to the work of bottom navigation.

2021-11-01 21:56 UTC, Blu3Parr0t commented on app/src/main/res/values/themes.xml
> +        <item name="colorPrimary">#fbcd1f</item>
Please include color in colors.xml

2021-11-01 21:56 UTC, Blu3Parr0t commented on app/src/main/res/layout/fragment_home_screen.xml
> +        android:text="Home screen fragment" />
If you don't need it don't add it.

2021-11-01 21:56 UTC, Blu3Parr0t commented on app/src/main/res/layout/fragment_display_screen.xml
> +        android:text="Display Screen Fragment" />
No hardcoded strings. If you don't need it. Don't add it.

2021-11-01 21:56 UTC, Blu3Parr0t commented on app/src/main/res/layout/activity_main.xml
> +        android:background="#1f1f39"
No hard coded colors.

2021-11-02 21:21 UTC, jjhuert99 approved these changes
all looks great

2021-11-03 14:44 UTC, Rafa311018 approved these changes

2021-11-03 15:33 UTC, Blu3Parr0t approved these changes
LGTM

2021-11-03 15:33 UTC, merged